### ISSUE TITLE
Decoder Network for Reconstruction

### ISSUE THREAD

**Issue by kdhasi** [ZHAOZHIHAO/ClusterRouting#1]
Hi,

The model works fine!

If possible, can I know for the decoder network mentioned in the paper, which capsule vectors were passed to reconstruct the input images?
I have tried using the direct output from final capsule layers and the concatenated vectors passed onto the classifier but couldn't generate results resembling the inputs.

Thank you!

**Comment by ZHAOZHIHAO** [comment]
In the paper, I wrote "Based on M-variant2, we change the number of last-layer capsules to 10, such that each last-layer capsule represents a class of the MNIST dataset. For an input im- age, we mask out all capsule vectors of the last layer except the one representing the input image’s class. This capsule vector is input to a decoder that reconstructs the input im- age. The decoder has the same architecture as in (Sabour et al., 2017), which consists of 3 fully connected layers with 512, 1024, and 784 (784 is the total number of pixels of an MNIST image) neurons, respectively. As shown in Figure 2, the proposed capsule networks produce capsules with disen- tangled representation."

This means that for the MNIST dataset, if the input digit is for example 5, the 5-th capsule vector is used to reconstruct the input digit. Don't forget that to make the reconstruction work, you need to train this reconstruction network in the training stage, which is same as the dynamic routing paper.

**Comment by kdhasi** [comment]
Got it. Thank you very much!
